#!/usr/bin/env python3
"""Regenerates docs/site-data.js from docs/site-status.md + the GitHub
Releases API, for the public landing page (see docs/site-status.md's
own header comment). Run by .github/workflows/site-data.yml on every
push to docs/site-status.md, on every published release, and on a
daily schedule as a safety net -- not meant to be run by hand except
to preview a change locally.

Deliberately dependency-free (stdlib only) so it needs nothing beyond
the python3 already on GitHub's runners.
"""
import json
import os
import re
import sys
import urllib.request
from datetime import datetime, timezone

REPO = os.environ.get("GITHUB_REPOSITORY", "joshuaclemons1/Rob-Everyone")
REPO_ROOT = os.path.join(os.path.dirname(__file__), "..", "..")
STATUS_MD = os.path.join(REPO_ROOT, "docs", "site-status.md")
OUT_JS = os.path.join(REPO_ROOT, "docs", "site-data.js")

# Same gotcha the in-game/launcher update checkers already ran into:
# every tag in this repo is marked prerelease, and /releases/latest
# unconditionally excludes prereleases -- it 404s here every time. The
# list endpoint (sorted newest-first) is the one that actually works.
RELEASES_URL = f"https://api.github.com/repos/{REPO}/releases?per_page=1"


def parse_sections(markdown_text):
    """Splits on '## Heading' lines, collects '- bullet' lines under
    each into a list. Headings are matched case-insensitively against
    a fixed set so a typo'd heading fails loudly instead of silently
    dropping a section."""
    sections = {"already in the build": [], "coming next": []}
    current = None
    for line in markdown_text.splitlines():
        heading = re.match(r"^##\s+(.*)", line)
        if heading:
            key = heading.group(1).strip().lower()
            current = key if key in sections else None
            continue
        bullet = re.match(r"^-\s+(.*)", line)
        if bullet and current:
            sections[current].append(bullet.group(1).strip())
    return sections["already in the build"], sections["coming next"]


def fetch_latest_release():
    req = urllib.request.Request(
        RELEASES_URL,
        headers={"Accept": "application/vnd.github+json", "User-Agent": "rob-everyone-site-data"},
    )
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    with urllib.request.urlopen(req, timeout=15) as resp:
        releases = json.load(resp)
    if not releases:
        return None
    r = releases[0]
    return {
        "version": r.get("tag_name"),
        "releaseDate": r.get("published_at"),
        "releaseUrl": r.get("html_url"),
    }


def main():
    with open(STATUS_MD, encoding="utf-8") as f:
        built, coming_next = parse_sections(f.read())

    release = fetch_latest_release()
    if release is None:
        print("warning: no releases found via the GitHub API; version/date fields will be omitted", file=sys.stderr)
        release = {"version": None, "releaseDate": None, "releaseUrl": None}

    data = {
        **release,
        "built": built,
        "comingNext": coming_next,
        "updatedAt": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    }

    js = "// Auto-generated by .github/scripts/build_site_data.py -- do not hand-edit.\n" \
         "// Edit docs/site-status.md instead; this regenerates on push.\n" \
         f"window.ROB_EVERYONE_DATA = {json.dumps(data, indent=2)};\n"

    with open(OUT_JS, "w", encoding="utf-8") as f:
        f.write(js)

    print(f"Wrote {OUT_JS}")
    print(json.dumps(data, indent=2))


if __name__ == "__main__":
    main()
